server:
  port: 8081


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:sqlserver://localhost:55535;databaseName=task_management;trustServerCertificate=true
    url: jdbc:mysql://localhost:3306/task_master
    username: root
    password: your_password
    hikari:
      maximum-pool-size: 10



  jpa:
    show-sql: off
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true
  application:
    name: task-management-service

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 510095165481-382ece7lvck30beqc5624vrt5922rju6.apps.googleusercontent.com
            client-secret: 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


  mail:
    password: skf2
    username: sandeepgfgjava@gmail.com
  main:
    banner-mode: off
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    listener:
      direct:
        consumers-per-queue: 5



#  sql:
#    init:
#      mode: always
logging:
  level:
    org.springframework.security: off
    org.springframework.security.oauth2: off
    org.springframework.amqp: off




rabbitmq:
  queue:
    name: task-queue
    analytics: task-analytics-queue

  exchange:
    name: task-notifications-exchange

  routing:
    key: task-notifications-routing-key
    analytics:
      key:  task-analytics-routing-key



upload:
  directory: D:\learnings\spring-uploadfile\src\main\resources\uploaded\


jwt:
  expiration: 3600000


#  server.port=8080
#  spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#  spring.datasource.url=jdbc:sqlserver://localhost:55535;databaseName=task_management;trustServerCertificate=true
#  spring.datasource.username=root
#  spring.datasource.password=password
#  spring.jpa.show-sql=false
#  spring.jpa.hibernate.ddl-auto=update
#  spring.application.name=task-management-service
#  spring.security.oauth2.client.registration.google.client-id=GOOGLE_CLIENT_ID
#  spring.security.oauth2.client.registration.google.client-secret=GOOGLE_SECRET_ID
